# Generated by Django 3.0.3 on 2020-08-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200830_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(default='No Category', max_length=64, unique=True),
        ),
    ]
