# Generated by Django 3.0.3 on 2020-08-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200831_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='last_bid',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('auction_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.AuctionListing')),
            ],
        ),
    ]
