# Generated by Django 3.1.6 on 2021-07-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200831_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.URLField(default='https://icon-library.com/images/no-image-icon/no-image-icon-0.jpg'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
